# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7cb1e1fb0785dc4b728b37cdfea30c696e79a1394b62391432c6e4f4f2520c3c563eb14241bdad84fd28408eee83c320de28a8ac25ce3840efa8daddbea25da

test:
  secret_key_base: ef35cca26d086edaa88b06dd668516501e1b046e425f4098682e73a4319a6da6ca4e283bdca7d6a0d1128ffc18114db54776d2cf3605e983898b8a9ae36c3dc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
